### ISSUE TITLE
Mouse movement issue

### ISSUE THREAD

**Issue by tsiiot** [TolikPylypchuk/SharpHook#100]
Two monitors, mouse movement is normal, but mouse movement fails for three monitors. The value of x is always at the top of the main screen. My device list: horizontal display for the main monitor, vertical display for the second and third monitors. The main and second displays are 4k, while the third display is 1080p

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! I will look into it in the nearest future.

**Comment by Barni6264** [comment]
Hello, I came across the same issue with 3 monitors on Win10.

**Screen setup:**
- left (ID:3, 1080p)
- middle (ID:2, this is the main display, 1080p)
- right (ID:1, 1024x768)

`MouseMoved` event gives 0;0 for the top left of the middle (main) screen, and negative values on the monitor to the left. (I guess that's good). However, when I feed the values back and try to simulate movements between screens, it doesn't work:

The cursor should move like this:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   left => middle => right      _(-1920 => 0 => 2900)_
but it moves like this instead:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   middle => right => gets stuck on edge of the right screen

**Comment by TolikPylypchuk** [comment]
I have fixed this issue and will release a new version with the fix soon. But I'm going to close this issue as a duplicate though since it's the same issue as #98. We can continue the discussion there.
