### ISSUE TITLE
Support for touch events

### ISSUE THREAD

**Issue by jhimes144** [TolikPylypchuk/SharpHook#101]
Hi,

This is an awesome library. Is it possible that we could get touch events as well?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking! I will have to look into it, but I'm currently not sure, so no promises.

**Comment by TolikPylypchuk** [comment]
It appears that global touch input handling is fundamentally different than keyboard or mouse input handling. Also, it's [not supported in libuiohook](https://github.com/kwhat/libuiohook/issues/62) and I'm not sure I will manage to implement it myself.

I'm going to close this issue as a won't-fix, but we can continue the discussion.

**Comment by jhimes144** [comment]
Thanks for looking into that!
