### ISSUE TITLE
Arrow keys simulate numpad arrow keys

### ISSUE THREAD

**Issue by BlackCoyote** [TolikPylypchuk/SharpHook#102]
Hey,

When simulating any of the arrow keys (VcUp, VcLeft, VcRight, VcDown) on windows 10 and 11, they seem to simulate the numpad-based arrow keys (shared with numpad numbers 8, 4, 6, 2) instead of the dedicated arrow keys.

For the most part, this will behave the same, but some applications only explicitly react to the dedicated arrow keys. I found that using [https://www.onlinemictest.com/keyboard-test/](https://www.onlinemictest.com/keyboard-test/) reliably lets you test this and see the difference between the real dedicated arrows and the simulated ones.

Hopefully you can figure out a way to simulate the dedicated arrow keys. Let me know if I can help in any way!

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! I will look into it.

Also, please don't share any links to russian websites, I'm sure there are better alternatives out there.

**Comment by BlackCoyote** [comment]
> Hi! Thanks for posting this issue! I will look into it.
> 
> Also, please don't share any links to russian websites, I'm sure there are better alternatives out there.

My apologies. I've updated the URL to a different keyboard tester on which the issue can also be replicated.

**Comment by TolikPylypchuk** [comment]
There was indeed a bug with simulating these keys on Windows. I've just released version 5.3.4 which fixes it, so this issue can be closed.

**Comment by BlackCoyote** [comment]
That's great! Nice work as always.
