### ISSUE TITLE
UioHookResult.SimulateTextEntry : Simulates only non-repeating characters.

### ISSUE THREAD

**Issue by Butcher-vj** [TolikPylypchuk/SharpHook#106]
I am trying to simulate text entry in a machine using using SharpHook.Native.UioHookResult.SimulateTextEntry.
If the string i want to simulate is like this means "112233", the simulatetextEntry is simualting only 123 ?
This is happening everywhere, but if the text is being simulated in a notepad means it works fine but if i use this simulation in like file explorer or browser for searching purpose like that it simulates only non repeating characters.

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! I will look into it.

**Comment by TolikPylypchuk** [comment]
I've fixed the bug, and will release a new version shortly.

**Comment by TolikPylypchuk** [comment]
I've just released version 5.3.5 which fixes this bug, so this issue can be closed.
