### ISSUE TITLE
Cannot use SharpHook with X64 app on Arm CPU

### ISSUE THREAD

**Issue by GuruGurra** [TolikPylypchuk/SharpHook#107]
Versions 5.3.0 and later cannot be used when building an X64 macOS app that is run under Rosetta on an Arm CPU.

Even though the project is published for the X64 platform, the included libuiohook.dylib file is for Arm64.

When run on macOS, the program crashes, and the exception in the log file lists the following:

"...libuiohook.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! I will look into it.

**Comment by TolikPylypchuk** [comment]
There was indeed a problem with the libuiohook builds for macOS - SharpHook provided the Arm64 build for both platforms. I've fixed this and will release a new version shortly.

**Comment by TolikPylypchuk** [comment]
I've released version 5.3.6 which fixes this problem, so this issue can be closed.
