### ISSUE TITLE
Mouse Event is still handled by windows when SuppressEvent = true

### ISSUE THREAD

**Issue by jjmdekroon** [TolikPylypchuk/SharpHook#109]
I am creating an desktop application for windows and mac. I use visual studio and maui application.

When I want to catch a mouse event and replace it with another command is this possible with the SharpHook package? I have added the RunAsync command in the App class. I override the CreateWindow and add an event handler to the window Created event. In this event handler I await the EventHook.RunAsync()

I use the TaskPoolGlobalHook and MouseClicked event handler. 

The mouseClicked handler is called and I check the e.data.button to determine the replacement. The mouse I use has some extra buttons which are visible as button4 or button5. In the mouseClicked event handler I use the EventSimulator to send a key when for instance the button4 mouse event is received.

But now both events are send to windows the button4 event and the simulated event.

The event handler of the TaskPoolGlobalHook had the following syntax:
private void OnMouseClicked(object? sender, MouseHookEventArgs e)

when i set the SuppressEvent to true windows still handles the button4 event. I expected that this event is not handled by windows anymore. 

I am not yet familiair with .net maui but what am I doing wrong?

**Comment by TolikPylypchuk** [comment]
Hello! Thanks for posting this issue! Unfortunately, this is expected behavior for `TaskPoolGlobalHook`. Suppressing events only works synchronously i.e. when the event handler is on the same thread, so you should use `SimpleGlobalHook` instead.
