### ISSUE TITLE
Simulating keyboard and mouse hook events on other applications

### ISSUE THREAD

**Issue by dannyshenl** [TolikPylypchuk/SharpHook#110]
Hey there,
﻿
Your code library looks incredibly well-crafted. It's far more straightforward to use on Windows compared to the Win32 API, and I'm really keen to utilize it.
﻿
I have a use case where I need to simulate sending hook events to the keyboard and mouse, targeting other specific form applications on a Windows 10 system. I haven't come across similar methods in the EventSimulator class. Do you think this library can achieve the functionality I'm after?
﻿
I'd appreciate your insights on this. Looking forward to your answer.

**Comment by TolikPylypchuk** [comment]
Hello! Thanks for asking! Do you mean that you'd like to send input messages to a specific window or application? If so, then I'm afraid that this library can't do that - it only sends global input events which the OS then handles as it sees fit (usually sending them to the foreground window).

**Comment by dannyshenl** [comment]
> Hello! Thanks for asking! Do you mean that you'd like to send input messages to a specific window or application? If so, then I'm afraid that this library can't do that - it only sends global input events which the OS then handles as it sees fit (usually sending them to the foreground window).

That's too regrettable. Thank you for your answer. I will close this issue
