### ISSUE TITLE
Button2 and Button3 are mixed up in MouseReleased event

### ISSUE THREAD

**Issue by Neakita** [TolikPylypchuk/SharpHook#119]
![image](https://github.com/user-attachments/assets/cfbc33e3-b799-45b6-bb74-08d7512a2bc5)

package version is 5.3.7

I guess it's necessary, so here is my OS info:
![image](https://github.com/user-attachments/assets/2e2d1ef0-e02a-48a4-ba9e-292c14202194)

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! There is indeed a problem with button 2 and 3 for mouse button release on Linux. I will fix this and release a new version in the next couple days.

**Comment by TolikPylypchuk** [comment]
I've just released version 5.3.8 which fixes this bug, so the issue can be closed.
