### ISSUE TITLE
Cursor state?

### ISSUE THREAD

**Issue by ZeoWorks** [TolikPylypchuk/SharpHook#27]
Hi, is it possible to find the cursor state? (visible, hidden) with sharphook?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking!

No, the underlying libuiohook library doesn't currently support it. If you want to add this as a feature, you should create an issue (or even a pull request) in the [original libuiohook repository](https://github.com/kwhat/libuiohook) though I should warn you that it's not currently under active development.
