### ISSUE TITLE
Multiple keyboards support?

### ISSUE THREAD

**Issue by breadnone** [TolikPylypchuk/SharpHook#3]
Managed to make this work in Unity3d with a bit of hack so it would work with il2cpp but I still have a problem detecting multiple keyboards.

libuiohook seems to provide the api, can we do this with SharpHook?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! Unfortunately, it appears that libuiohook doesn't support multiple keyboards (at least [this issue](https://github.com/kwhat/libuiohook/issues/63) says that it's not supported and not going to be supported). So there's not much that I can do about it :(
