### ISSUE TITLE
NRE on newing object

### ISSUE THREAD

**Issue by LiorBanai** [TolikPylypchuk/SharpHook#33]
Hi.
what could be the reason for null reference exception on newing the TaskGlobalHook on x64 build)?

**Comment by TolikPylypchuk** [comment]
Hi! I'm going to need a little more info on this. Could you please share the exception stack trace?

**Comment by LiorBanai** [comment]
There isn't one. Just on the ctor![hook_error.jpg](https://user-images.githubusercontent.com/36262995/214277030-8998a60b-273d-4cc2-a29d-57cf98f69633.jpg)

**Comment by LiorBanai** [comment]
it does not seems related to your library but to some optimization of the code:
```csharp
       if (condition)
            {
                var hook = new TaskPoolGlobalHook();
                ...
}

```

if the condition is false and in the debugger I enter the if block it fails. If the condition is true it works..

**Comment by LiorBanai** [comment]
![nre.gif](https://user-images.githubusercontent.com/36262995/214281744-ebbf9322-2701-426a-a75c-65259923085b.gif)

**Comment by TolikPylypchuk** [comment]
I think this is an issue of the debugger - you change the code at runtime and something weird happens. Since it's not related to SharpHook, I'm going to close this issue.
