### ISSUE TITLE
Does it support .net xamarin android apps?

### ISSUE THREAD

**Issue by dvaca-sml** [TolikPylypchuk/SharpHook#34]
I tried to test this out in a simple .net xamarin android app (https://github.com/xamarin/AndroidX). But I could not get it to work. We were able to get it to work with maui but not xamarin android so is it not supported or is there maybe something I might be doing wrong?

For reference, I pushed my simple app into this repo. The SharpHook code is in file MainActivity.cs. 
https://github.com/dvaca-sml/XamarinSharpHookTestApp2

The app builds and there are no run time errors. But I'm not able to capture any key events. 

Also I added logs to check the hook's IsRunning and IsDisposed flags and they are always false.

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking!

Unfortunately, SharpHook doesn't support Android. libuiohook, the library on which SharpHook is based, only supports Windows, macOS, and Linux. So SharpHook won't work on Android, iOS and other OSes.
