### ISSUE TITLE
SharpHook doesn't work on Mac Catalyst

### ISSUE THREAD

**Issue by TolikPylypchuk** [TolikPylypchuk/SharpHook#35]
As @karthitect said in discussion #22, SharpHook doesn't work in a MAUI app on macOS as it uses Mac Catalyst - it fails with `DllNotFoundException` when trying to access libuiohook. I'm not sure it's going to work at all, but this needs to be investigated - maybe the libuiohook build can be updated to work on Mac Catalyst.

**Comment by TolikPylypchuk** [comment]
SharpHook cannot work on Mac Catalyst until libuiohook can be built for it. I've tried configuring it but didn't manage to do that. I've created [an issue in the original libuiohook repo](https://github.com/kwhat/libuiohook/issues/168) to add a Mac Catalyst build.

**Comment by TolikPylypchuk** [comment]
Finally, I've managed to add support for Mac Catalyst in SharpHook, although it was really painful. It will be available in version 5.0.0.

**Comment by LocutusOfPenguin** [comment]
Hi,

i would need support for Drag&Drop for Mac / Maui very urgently.

When can we expect this 5.0 to be released?
If it takes longer, perhaps you can create a branch for it...i can even help in some way (maybe).

Thanks.

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for your interest!

There are still a couple things I need to do before releasing 5.0 - it's a much larger release than I've initially anticipated. I think I'll be done in a couple weeks.

If you can't or don't want to wait for the release, you can use the nupkg files that are built in GitHub actions - they are built for every commit to the `master` branch (check out the `sharphook-build` artifact). They are mostly stable (but there could still be some breaking changes) and I think they can be used in development - but not in production, obviously. Also, they all have version 5.0.0 which may be inconvenient.

**Comment by JohnKesko** [comment]
@TolikPylypchuk  Thank you for providing MacCatalyst support.. wish I looked into this thread a bit earlier instead of wasting a couple of hours trying to figure out what was wrong lol.

Anyway, just fyi - installed version 5.0.0 and it works great!

**Comment by TolikPylypchuk** [comment]
Yeah, happens to the best of us :)

That's great to hear that Mac Catalyst support works well! Version 5.0.0 is basically done - I just want to write the docs and test it on various platform configurations - so I think it's going to be a matter of days.

**Comment by TolikPylypchuk** [comment]
I've just released version 5.0.0 so this issue can finally be closed.
