### ISSUE TITLE
Simulate on second monitor

### ISSUE THREAD

**Issue by aspmaker** [TolikPylypchuk/SharpHook#36]
Hello, how can we mouse click simulate on second monitor?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking! Unfortunately, libuiohook - the library which SharpHook uses under the hood - [doesn't support multimonitor setup](https://github.com/TolikPylypchuk/libuiohook/blob/1ece4c4c24958d6ede0cba867f1a1cb3387f81f8/src/windows/post_event.c#L114). If you need this functionality, then you should open an issue in the [original libuiohook repo](https://github.com/kwhat/libuiohook) though I should warn you that it's not currently under active development.

**Comment by TolikPylypchuk** [comment]
Hi! Thanks to [this pull request in libuiohook](https://github.com/TolikPylypchuk/libuiohook/pull/1) this is now supported on Windows starting with version 4.0.1!
