### ISSUE TITLE
Different keyboard layouts

### ISSUE THREAD

**Issue by Berets** [TolikPylypchuk/SharpHook#38]
Hi, first of all thank you for the awsome work.

Is there a way to handle different keyboard layout?
Maybe sending scan code instead of key code?

Thank you

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for using SharpHook!

Could you please clarify what you mean a little? Do you mean that you'd like to know which character was typed inside the keyboard hook? Or do you want to handle different keyboard layouts when simulating keyboard events? Or maybe something else?

Also, I should add that libuiohook (and SharpHook by extension) doesn't really know anything about keyboard layouts.

**Comment by Berets** [comment]
Yes on simulating, seems it works only with US layout.
Probably a limitation of libuiohook

**Comment by TolikPylypchuk** [comment]
If you mean that you'd like to simulate typing different characters, then yes, it's not supported as key codes are very different from characters, and libuiohook only works with key codes (and scan codes, but they also don't have much to do with characters themselves). I've created [an application which works with typed characters](https://github.com/TolikPylypchuk/KeyboardSwitch) (which was the reason SharpHook was created in the first place) and it's really non-trivial to understand which keys need to be pressed to produce a certain character.

I'm closing this issue as "won't fix", but we can continue the discussion if you'd like.

**Comment by TolikPylypchuk** [comment]
Hi, @Berets! I've just released version 5.0.0 which adds a new feature - simulating arbitrary text, so this issue can be closed as completed.
