### ISSUE TITLE
On MacOS x64, Reactive Global Hooks stop working after the first event.

### ISSUE THREAD

**Issue by DrBenvey** [TolikPylypchuk/SharpHook#42]
Works great for Windows and Linux. On MacOS (x64 Big Sur) Reactive Global Hooks stop working after the first event.

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for opening the issue! It looks like something similar to the issue described in https://github.com/TolikPylypchuk/SharpHook/issues/39#issuecomment-1463800163. Unfortunately, I cannot fix this issue at the moment as I don't have a Mac, but as soon as I get the opportunity, I'll take a look at it.

**Comment by DrBenvey** [comment]
I don't have a Macbook too. I took it for a couple of days just to build the project. And half of it doesn't work as expected. Let's hope for the help of the community.

**Comment by FaithBeam** [comment]
@DrBenvey Hello! Can you post a small sample, please?

**Comment by DrBenvey** [comment]
> @DrBenvey Hello! Can you post a small example program, please?

C# .net 7 console app Program.cs

```
using SharpHook;
using SharpHook.Reactive;
using System.Reactive.Linq;

int oS = GetOS();
RunSureillance runSureillance=new RunSureillance(oS);
Console.WriteLine("doind some other work");
Console.ReadLine();

///
///1 is Windows
///2 is Linux
///3 is MacOS
///-1 is smth went wrong
///
int GetOS()
{
    if (OperatingSystem.IsWindows())
    {
        Console.WriteLine("IsWindows");
        return 1;
    }        
    else if (OperatingSystem.IsLinux())
    {
        Console.WriteLine("IsLinux");
        return 2;
    }       
    else if (OperatingSystem.IsMacOS())
    {
        Console.WriteLine("IsMacOS");
        return 3;
    }        
    else
        return -1;
}

public class RunSureillance
{
    private int OS { get; set; }
    public RunSureillance(int oS)
    {
        OS=oS;
        switch (OS)
        {
            case 1:
                Run_timer_ActivityReactive();
                break;
            case 2:
                Run_timer_ActivityReactiveAsync();
                break;
            case 3:
                Run_timer_ActivityReactiveAsync();
                break;
        }
    }
    public void Run_timer_ActivityReactive()
    {
        var hook = new SimpleReactiveGlobalHook();
        hook.MouseClicked.Subscribe(OnMouseEvent);
        hook.MouseWheel.Subscribe(OnMouseEvent);
        hook.KeyPressed.Subscribe(e => OnKeyPressed(e, hook));
        hook.MouseMoved
            .Throttle(TimeSpan.FromSeconds(1))
            .Subscribe(OnMouseEvent);
        hook.RunAsync();
    }

    public async Task Run_timer_ActivityReactiveAsync()
    {
        var hook = new SimpleReactiveGlobalHook();
        hook.MouseClicked.Subscribe(OnMouseEvent);
        hook.MouseWheel.Subscribe(OnMouseEvent);
        hook.KeyPressed.Subscribe(e => OnKeyPressed(e, hook));
        hook.MouseMoved
            .Throttle(TimeSpan.FromSeconds(1))
            .Subscribe(OnMouseEvent);
        hook.RunAsync();
    }

    private void OnMouseEvent(HookEventArgs e)
    {
        Console.WriteLine("mouseUpdate");
    }

    private void OnKeyPressed(KeyboardHookEventArgs e, IReactiveGlobalHook hook)
    {
        Console.WriteLine("keyPress");
    }
}
```
1. If you start for Linux in the same way as for Windows, then we don’t go through the initialization of the surveillance class below. Therefore, I used an asynchronous function.

2. for macOS noticed that it dies after the first click/wheel/key press.
If you recreate the hook after every key press or mouse wheel scroll, it works, but clicks still kill it.

**Comment by TolikPylypchuk** [comment]
Looking at the code, it appears that the issue is the following: for the global hook to work on macOS it requires a main run-loop to be present (a run-loop is basically an event loop on macOS) - that is, it requires a run-loop on the main thread. If you run the hook itself on the main thread, then it takes care of the run-loop by itself. If you're in a GUI application, e.g. Avalonia, then the framework will take care of the run-loop. But if you run a hook on some other thread inside a console application, then you need to take care of the run-loop yourself. I've described this behavior [in the docs](https://sharphook.tolik.io/v4.2.0/articles/native.html#working-with-the-hook-itself), but I guess it's easy to miss.

Try to run the hook on the main thread and see how it goes. If the problem persists, then it's something else.

**Comment by DrBenvey** [comment]
> Looking at the code, it appears that the issue is the following: for the global hook to work on macOS it requires a main run-loop to be present (a run-loop is basically an event loop on macOS) - that is, it requires a run-loop on the main thread. If you run the hook itself on the main thread, then it takes care of the run-loop by itself. If you're in a GUI application, e.g. Avalonia, then the framework will take care of the run-loop. But if you run a hook on some other thread inside a console application, then you need to take care of the run-loop yourself. I've described this behavior [in the docs](https://sharphook.tolik.io/v4.2.0/articles/native.html#working-with-the-hook-itself), but I guess it's easy to miss.
> 
> Try to run the hook on the main thread and see how it goes. If the problem persists, then it's something else.

ok. code from your sample works fine in main thread. 

```
using SharpHook;
using SharpHook.Reactive;
using System.Reactive.Linq;

var hook = tmp.CreateHook();
hook.Run();

static IReactiveGlobalHook CreateHook()
{
    var hook = new SimpleReactiveGlobalHook();
    //key
    hook.KeyReleased.Subscribe(OnHookEventKeyReleased);
    hook.KeyTyped.Subscribe(OnHookEventKeyTyped);
    hook.KeyPressed.Subscribe(OnHookEventKeyPressed);
    //mouse
    hook.MouseClicked.Subscribe(OnHookEventMouse);
    hook.MouseMoved
        .Throttle(TimeSpan.FromSeconds(1))
        .Subscribe(OnHookEventMouse);
    hook.MouseWheel.Subscribe(OnHookEventMouse);
    return hook;
}
//key
static void OnHookEventKeyReleased(HookEventArgs e) =>
    Console.WriteLine($"OnHookEventKeyReleased");

static void OnHookEventKeyTyped(HookEventArgs e) =>
    Console.WriteLine($"OnHookEventKeyTyped");

static void OnHookEventKeyPressed(HookEventArgs e) =>
    Console.WriteLine($"KeyPressed");

//mouse
static void OnHookEventMouse(HookEventArgs e) =>
    Console.WriteLine($"Mouse");
```

P.S. keyboard events doesn't work without permission for Input monitoring.
![Screenshot 2023-04-11 at 11 13 39](https://user-images.githubusercontent.com/48998000/231100887-ad639ea2-8171-42f2-93e3-3a07ba68b4a0.png)

P.P.S. hook.RunAsync(); doesn't work as it starts a new thread(. I'm using asp net core + ElectronNet(https://github.com/ElectronNET/Electron.NET) for desktop app. I suppose, that it's not a problem to make app.Run in new thread.

**Comment by TolikPylypchuk** [comment]
If you're using Electron.NET (or any desktop framework really) then it should get you covered on the main run-loop thing. This is an issue only in console apps or background apps.

And yes, macOS doesn't give apps access to keyboard/mouse hooks without the accessibility permission. I should make it more clear in the docs.
