### ISSUE TITLE
Extend the KeyCode list?

### ISSUE THREAD

**Issue by GuruGurra** [TolikPylypchuk/SharpHook#46]
The KeyCode lits lacks several ordinary characters, like " ( ) & % ¤ # 

How can I extend the list to make it more complete?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking! `KeyCode` doesn't map one-to-one to various characters. You get `(` by pressing `Shift+9`, so really, the `(` key doesn't exist, it's just the `9` key. All the characters you pointed out as examples are actually typed using `Shift` + some other key.

I'm going to close this issue, but we can continue the discussion if you'd like.
