### ISSUE TITLE
Any reactive helpers for listening to key shortcuts?

### ISSUE THREAD

**Issue by grofit** [TolikPylypchuk/SharpHook#50]
I have just found this library and it even has a reactive extensions layer which is brilliant.

For my scenario I need to allow users to be able to set any key combos they want for shortcuts i.e `ctrl` + `a` + `f`` and as this seems like a common situation I wasnt sure if there was any helper libs/extensions anywhere which wrapped up this sort of use case?

If not no problem as im sure I can do a rx buffer for a period on keypress for a short interval and just check all inputs during that period have the required inputs, but I didn't want to re-invent the wheel if an extension/helper already existed for this?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking! Unfortunately, SharpHook doesn't provide any helpers for composing multiple key events. I'm sure that with Rx.NET it's quite easy to do, so I'll consider adding them sometime in the future.

**Comment by grofit** [comment]
No worries, incase anyone else wants to do something similar here is a simple set of extension methods I made to support the usecase, it may not be super performant but it seems to work:

```csharp
public static class InputExtensions
{
    public static ModifierMask[] AllMasks = Enum.GetValues<ModifierMask>()
        .Where(x => x != ModifierMask.None)
        .ToArray();

    public static ModifierMask[] GetActiveMasks(this ModifierMask mask)
    {
        return AllMasks
            .Where(x => mask.HasFlag(x))
            .ToArray();
    }
    
    public static bool HasAnyMasks(this ModifierMask mask, ModifierMask[] maskKeys)
    { return maskKeys.All(x => mask.HasFlag(x)); }

    public static bool HasOnlyMasks(this ModifierMask mask, ModifierMask[] maskKeys)
    {
        var activeMasks = GetActiveMasks(mask);
        return activeMasks.Length == maskKeys.Length && activeMasks.All(maskKeys.Contains);
    }
    
    public static bool Matches(this IReadOnlyCollection<KeyCode> activeKeys, IReadOnlyCollection<KeyCode> expected)
    {
        return activeKeys.Count == expected.Count &&
               activeKeys.All(expected.Contains);
    }
    
    public static IObservable<Unit> ListenFor(this IReactiveGlobalHook hook, ModifierMask[] maskKeys, params KeyCode[] keys)
    {
        return hook.KeyPressed
            .Where(x => x.RawEvent.Mask.HasOnlyMasks(maskKeys))
            .GroupByUntil(_ => true, _ => Observable.Timer(TimeSpan.FromMilliseconds(150)))
            .SelectMany(x => x.Select(y => y.Data.KeyCode).ToArray())
            .Where(x => x.Matches(keys))
            .Select(x => Unit.Default);
    }
}
```

**Comment by MarcoMedrano** [comment]
> No worries, incase anyone else wants to do something similar here is a simple set of extension methods I made to support the usecase, it may not be super performant but it seems to work:

Hi @grofit , I have no idea of Rx.Net but the complexity to listen to a combination like ctrl+c+c took me to this place, I am trying to use your extension methods but not sure what I am doing wrong, a little help please?

```csharp
IReactiveGlobalHook hook = new SimpleReactiveGlobalHook(runAsyncOnBackgroundThread: true);
hook.RunAsync().Subscribe();

hook.ListenFor([ModifierMask.Ctrl], [KeyCode.VcC, KeyCode.VcC]).Subscribe(OnKeyPressed);
```
I installed both `SharpHook.Reactive` and `System.Reactive` but my `void OnKeyPressed(Unit unit)` is never called.
I also tried simpler combinations like ctrl+b, but no luck.

**Comment by grofit** [comment]
To my knowledge it all worked as I was using it in the Strem App.

It does only provide a 150ms window to provide the input, so it may be that stuff needs a bigger window, and there may be a better way to do all this, but at the time this was the quickest way to do what I needed so I could move on to the other bits.

**Comment by TolikPylypchuk** [comment]
Hi @MarcoMedrano! I think the problem is with `ModifierMask.Ctrl`. This mask includes _both_ left and right <kbd>Ctrl</kbd> keys and should be used for comparison (e.g. `event.Mask & ModifierMask.Ctrl != ModifierMask.None`). Using it as a parameter for `HasFlag` or similar operations will not work as expected. Could you please try listening for `ModifierMask.LeftCtrl` to see whether it works? If it does, then `HasAnyMasks` and `HasOnlyMasks` should be refactored to take composite masks (`Ctrl`, `Alt`, `Shift`, and `Meta`) into consideration.

**Comment by MarcoMedrano** [comment]
Thank you @grofit, I increased the time to 500 and removed this line `activeKeys.Count == expected.Count &&` and Ctrl+c+c worked, although when I press them quick it does not catch it. By chance any idea?

Yes @TolikPylypchuk yup Ctrl key was one of my issues. Thanks for such awesome lib!

**Comment by grofit** [comment]
Maybe one thing that is also catching you out is that it expects the mod keys to be the first thing pressed I think THEN it checks to see what other keys have been pressed within the window, so maybe just ensure the mod key is pressed over so slightly before the others :D

As mentioned my solution is probably not great so you may be able to just grab all key inputs within an interval when you have a key pressed and see if any of the keys are the ones you want, but my concern with that though was potentially grabbing any and all keypresses would be a bit spammy.
