### ISSUE TITLE
Missing License Information In Nuget metadata

### ISSUE THREAD

**Issue by LiorBanai** [TolikPylypchuk/SharpHook#51]
Hi,
Could the license information be added to the nuget information?
it is good to add it so it will be shown in Visual Studio nuget management.

for example, Iuse the following ```<PackageLicenseExpression>MIT</PackageLicenseExpression>''' in my nugets:

	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryType>git</RepositoryType>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

**Comment by LiorBanai** [comment]
Great. thansk for the fast response.
btw I'm not sure both ```	<PackageLicenseExpression>MIT</PackageLicenseExpression>
``` and the ```<PackageLicenseFile>LICENSE</PackageLicenseFile>``` are compatible together.. maybe the PackageLicenseFile is no longer needed?

**Comment by TolikPylypchuk** [comment]
Huh, yeah, you're right. I can just the remove the license file altogether.

**Comment by LiorBanai** [comment]
Ignore my last edits :)

**Comment by TolikPylypchuk** [comment]
What do you mean? `PackageLicenseFile` really isn't needed if `PackageLicenseExpression` is present.

**Comment by LiorBanai** [comment]
I  accidentally re-edit my orginal message. Yeah it is not needed if expression is used

**Comment by TolikPylypchuk** [comment]
I've just released version 5.0.0 which fixes this issue so it can be closed now.
