### ISSUE TITLE
How to detect the key combinations such as Control+C via TaskPoolHook?

### ISSUE THREAD

**Issue by akash07k** [TolikPylypchuk/SharpHook#6]
I'm trying to detect the key presses such as:
Control+C, but it is not working.
Example below:
        private static void OnKeyReleased(Object? sender, KeyboardHookEventArgs e)
        {
//            Console.WriteLine(e.RawEvent);
if(e.RawEvent.Mask.HasFlag(ModifierMask.Ctrl) && e.Data.KeyCode == KeyCode.VcQ)
            {
                Console.Beep(800, 300);
            }
        }

Any help please?

**Comment by akash07k** [comment]
It worked now.
I had to change the code like this:
        private static void OnKeyReleased(Object? sender, KeyboardHookEventArgs e)
        { 
//            Console.WriteLine(e.RawEvent);
if(e.RawEvent.Mask.HasFlag(ModifierMask.LeftCtrl) && e.RawEvent.Mask.HasFlag(ModifierMask.LeftShift) && e.Data.KeyCode == KeyCode.VcQ)
            {
                Console.Beep(800, 300);
            }
        }

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue!

`ModifierMask.Ctrl` is defined as both `ModifierMask.LeftCtrl` and `ModifierMask.RightCtrl`, so writing `e.RawEvent.Mask.HasFlag(ModifierMask.Ctrl)` will check whether the event occurred when _both_ Ctrl keys were pressed.

Instead, you can do this:

```
e.RawEvent.Mask & ModifierMask.Ctrl != ModifierMask.None
```

This looks a little less readable, but it checks whether _any_ Ctrl key is pressed, not just the left one.

**Comment by akash07k** [comment]
Ok, thanks a lot bro.
I'm implementing it like this.
