### ISSUE TITLE
Shift - Home/End not select the text row

### ISSUE THREAD

**Issue by Berets** [TolikPylypchuk/SharpHook#62]
Hi, i noticed that SimulateKeyPress for Shift and Home or End to select a text row don't work.
The cursor go to the start of text line or to end, but it don't select the text.

Could be a issue of libuiohook?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking! I'd like some more info to understand the problem and how to fix it.
1. Which OS are you using?
2. Could you please share a minimal reproducible code?
3. Could you please share the relevant [libuiohook debug logs](https://sharphook.tolik.io/v5.0.0/articles/logging.html)?

**Comment by TolikPylypchuk** [comment]
There hasn't been any activity in this issue for more than a month, so I'm going to close it, but I can reopen it if you provide more info.
