### ISSUE TITLE
Mac OS double click not working

### ISSUE THREAD

**Issue by nodminger** [TolikPylypchuk/SharpHook#63]
Double click works well in Windows, but in Mac it does not work. Single click and right click works fine. My Mac version is Ventura.

```
simulator.SimulateMousePress(MouseButton.Button1);
simulator.SimulateMouseRelease(MouseButton.Button1);
simulator.SimulateMousePress(MouseButton.Button1);
simulator.SimulateMouseRelease(MouseButton.Button1);
```

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! I will look into it, but in the meantime, as a workaround, could you please try it with a small delay between the clicks to see whether it works?

**Comment by TolikPylypchuk** [comment]
Ok, I've tried to reproduce the issue and it really is a bug. Two mouse events are actually emitted (which can be verified with a global hook), but applications simply ignore the fact that it's a double-click. There is a way to tell applications the number of clicks so I'll add overloads of `SimulateMousePress` and `SimulateMouseRelease` which will include the number of clicks.

They will most probably have the following form:

```c#
// The second parameter specifies the number of clicks - this way applications will understand that it's a double-click
simulator.SimulateMousePress(MouseButton.Button1, 1);
simulator.SimulateMouseRelease(MouseButton.Button1, 1);
simulator.SimulateMousePress(MouseButton.Button1, 2);
simulator.SimulateMouseRelease(MouseButton.Button1, 2);
```

**Comment by nodminger** [comment]
> Hi! Thanks for posting this issue! I will look into it, but in the meantime, as a workaround, could you please try it with a small delay between the clicks to see whether it works?

I have tried with delay and it still had the same issue.

**Comment by nodminger** [comment]
> Ok, I've tried to reproduce the issue and it really is a bug. Two mouse events are actually emitted (which can be verified with a global hook), but applications simply ignore the fact that it's a double-click. There is a way to tell applications the number of clicks so I'll add overloads of `SimulateMousePress` and `SimulateMouseRelease` which will include the number of clicks.
> 
> They will most probably have the following form:
> 
> ```cs
> // The second parameter specifies the number of clicks - this way applications will understand that it's a double-click
> simulator.SimulateMousePress(MouseButton.Button1, 1);
> simulator.SimulateMouseRelease(MouseButton.Button1, 1);
> simulator.SimulateMousePress(MouseButton.Button1, 2);
> simulator.SimulateMouseRelease(MouseButton.Button1, 2);
> ```

Thank you very much for your response. I attempted the solution you provided, but I encountered an error. I believe I may have made a mistake. Could you please review this?

My Code:

```
using SharpHook;
using SharpHook.Native;

class Program
{
    static void Main()
    {
        Thread.Sleep(5000);
        var simulator = new EventSimulator();    

        simulator.SimulateMouseMovement(2480, 645);
        Thread.Sleep(500);
        simulator.SimulateMousePress(MouseButton.Button1, 1);
        simulator.SimulateMouseRelease(MouseButton.Button1, 1);
        simulator.SimulateMousePress(MouseButton.Button1, 2);
        simulator.SimulateMouseRelease(MouseButton.Button1, 2);
        Thread.Sleep(1000);
        Console.WriteLine("done");
        Console.ReadLine();
    }
}
```

Error:
`/Users/macmini/Projects/test/test/Program.cs(19,19): Error CS7036: There is no argument given that corresponds to the required parameter 'button' of 'EventSimulator.SimulateMousePress(short, short, MouseButton)' (CS7036) (Test)`

got this same error for line 13,14,15,16

**Comment by TolikPylypchuk** [comment]
Well, yes, the code above will lead to an error, because I haven't yet implemented this :)

I will release version 5.1.0 shortly which will contain the methods I've described.

**Comment by nodminger** [comment]
Alright, thank you!

**Comment by TolikPylypchuk** [comment]
Version 5.1.0 which contains the fix has been released today. Now simulating multiple clicks on macOS looks like this:

```c#
// The second parameter specifies the number of clicks - this way applications will understand that it's a double-click
simulator.SimulateMousePress(MouseButton.Button1, 1);
simulator.SimulateMouseRelease(MouseButton.Button1, 1);
simulator.SimulateMousePress(MouseButton.Button1, 2);
simulator.SimulateMouseRelease(MouseButton.Button1, 2);
```
