### ISSUE TITLE
Is there any way to get X,Y position of the caret?

### ISSUE THREAD

**Issue by invisionweb** [TolikPylypchuk/SharpHook#65]
I want to access the X,Y position of the caret/cursor after KeyPressed event is triggered. The application may be any application running. Please help :)

```
simulator = new EventSimulator();

//GlobalHookBase hook = new TaskPoolGlobalHook();
SimpleGlobalHook hook = new SimpleGlobalHook();
hook.KeyPressed += OnKeyPressed;
hook.MouseClicked += OnMouseClicked;
//hook.Run();
await hook.RunAsync();

private void OnKeyPressed(object sender, KeyboardHookEventArgs e)
{
}
```

**Comment by invisionweb** [comment]
@TolikPylypchuk Do you need further information? Do I have to submit codes?..or describe the problem in details?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking!

Getting the caret position and getting the cursor position are two very different things, so I'll answer them individually.

Getting the cursor position is supported only for mouse events. If you need cursor position elsewhere, then you have to keep it in a variable and update it every time the mouse moves, like this:

```c#
var cursorCoordinates = new Point(0, 0);

hook.MouseMoved += OnMouseMoved;
hook.MouseDragged += OnMouseMoved;

void OnMouseMoved(object? sender, MouseHookEventArgs e) =>
    cursorCoordinates = new Point(e.Data.X, e.Data.Y);
```

Of course, it has a downside - the mouse has to be moved at least once for this to start tracking coordinates. We can take care of this by simulating moving the cursor by one pixel:

```c#
var simulator = new EventSimulator();
simulator.SimulateMouseMovementRelative(1, 0);  // Move the cursor by one pixel
simulator.SimulateMouseMovementRelative(-1, 0); // Optionally move it back
```

Please also note that if you're running the app on Windows then you need to make it DPI-aware for it to work correctly on high-DPI screens.

Now, getting the caret position (the blinking I-beam that's present in text fields when you're typing text) is a very different thing. SharpHook doesn't provide this ability. It's really non-trivial, and in many cases it's simply impossible. Let's hope that you've meant that you need to keep track of the current cursor position, not the caret position :)

**Comment by invisionweb** [comment]
@TolikPylypchuk Thank you very much for answering. I want to keep track of the caret (blinking I-beam present in text fields) position. Can you suggest me some ways to do it, if SharpHook doesn't provide this ability? I liked the SharpHook library a lot :)

**Comment by TolikPylypchuk** [comment]
To be honest, I'm not sure. I've looked at some examples on StackOverflow, and that's it. And I only looked at Windows examples. I don't know if it's even possible on macOS or Linux.

You'll have to research and implement it on your own unfortunately.

I'm going to close this issue, but we can continue the discussion if you'd like.
