### ISSUE TITLE
KeyChar is not defined

### ISSUE THREAD

**Issue by magals** [TolikPylypchuk/SharpHook#69]
On all keys the character type '?' is always output. RawEvent.Keyboard.RawKeyChar = 65535

![image](https://github.com/TolikPylypchuk/SharpHook/assets/15940153/17f78652-8544-4a21-81f6-3046308a9adb)

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking! `KeyChar` and `RawKeyChar` are not available in the `KeyPressed` event. You need to subscribe to the `KeyTyped` event instead - then you'll be able to use `KeyChar`. Note that not all key presses lead to `KeyTyped` events. For example, if you press `Ctrl` it will not lead to a `KeyTyped` event.
