### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by eyaldar** [TolikPylypchuk/SharpHook#72]
Hi,

Let me start by saying that this looks like a very promising library, that being said I have a small concern about licensing:
I see that **SharpHook** is listed as MIT license, but **libuiohook** has a GPL license, I also see that **SharpHook** directly reference **libuiohook**, doesn't that make SharpHook have a GPL license?
Or is it not because you only reference libuiohook as a dynamic library?

Thanks in advance!

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking!

GitHub infers libuiohook's license incorrectly - it's actually LGPL. There are two license files in the repository - [COPYING.md](https://github.com/TolikPylypchuk/libuiohook/blob/9027a77d597da721134d5652d77f293cec76f0b9/COPYING.md) and [COPYING.LESSER.md](https://github.com/TolikPylypchuk/libuiohook/blob/9027a77d597da721134d5652d77f293cec76f0b9/COPYING.LESSER.md). I guess GitHub only takes the first file into consideration.

As far as I know, linking LGPL-licensed projects to MIT-licensed projects is perfectly fine.
