### ISSUE TITLE
IsEventSimulated true when it isn't

### ISSUE THREAD

**Issue by JMPSequeira** [TolikPylypchuk/SharpHook#77]
OS Name	Microsoft Windows 11 Pro
Windows Version 10.0.22631 Build 22631

SharpHook Version 5.2.0

I'm using your lib and if a key is pressed the IsEventSimulated is always true.
I think the bit operation should be bitwise And and not Or [IsEventSimulated](https://github.com/TolikPylypchuk/SharpHook/blob/adddf0cb23230209c6ac481e091a318ce6890890/SharpHook/HookEventArgs.cs#L29)

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for noticing the problem! I will fix it shortly.

**Comment by TolikPylypchuk** [comment]
I've just released version 5.2.1 which fixes this bug, so this issue can be closed.
