### ISSUE TITLE
TaskPoolGlobalHook not running in MAUI macOS

### ISSUE THREAD

**Issue by m1adow** [TolikPylypchuk/SharpHook#82]
Hi! I want to use your library but I can't get it to work on macOS. I have implemented service that will listen to keyboard it works fine on Windows but not on macOS.

```C#
public KeyboardHookService()
{
    var hook = new TaskPoolGlobalHook();
    hook.KeyPressed += OnKeyPressed;
    hook.Run();
}
```
 When `hook.Run()` executed asking for permissions dialog appears.
<img width="473" alt="Dialog" src="https://github.com/TolikPylypchuk/SharpHook/assets/84251113/e3cfbcd7-67b1-44a8-8f42-cf8c911a9952">

And after giving permission nothing happened and method never ends.
<img width="478" alt="Permission" src="https://github.com/TolikPylypchuk/SharpHook/assets/84251113/2bbcd081-ea83-4dc5-91d2-5760850d3236">

So how to fix it?

MAUI
.net 7.0
macOS Sonoma 14.2.1

**Comment by m1adow** [comment]
Hi! Thanks for your response. I have checked issue that you provided, but it didn't help me. I got no response from hook. I certainly gave `Accessibility` and 'Input Monitoring' permissions. I have expanded code sample for debug reasons but none events actually invoked, even `HookEnabled`. On windows everything working fine.

```C#
private readonly TaskPoolGlobalHook hook;

public KeyboardHookService()
{
    this.hook = new TaskPoolGlobalHook();
    this.hook.MouseClicked += Test;
    this.hook.MouseDragged += Test;
    this.hook.MouseMoved += Test;
    this.hook.MousePressed += Test;
    this.hook.MouseReleased += Test;
    this.hook.MouseWheel += Test;
    this.hook.KeyReleased += Test;
    this.hook.KeyPressed += Test;
    this.hook.KeyTyped += Test;
    this.hook.KeyPressed += OnKeyPressed;
    this.hook.HookEnabled += OnHookEnabled;
    this.hook.RunAsync();
}

private void Test(object sender, EventArgs e)
{

}

private void OnHookEnabled(object sender, HookEventArgs e)
{
    Debug.WriteLine("Hook started");
}
```

So what can you advice me more? I appreciate your help😊

**Comment by TolikPylypchuk** [comment]
Huh, this is certainly interesting. `HookEnabled` not being called means that the hook doesn't even fully initialize inside libuiohook. I will try to locate the issue, but cannot promise anything since it worked for me on MAUI the last time I've checked.

**Comment by TolikPylypchuk** [comment]
Hi @m1adow! Sorry for the long delay, but I've tried running a MAUI app on macOS and everything works on my machine - the events are raised without problems. Could you please provide a minimal project where the problem can be reproduced?

**Comment by TolikPylypchuk** [comment]
It's been almost a month since my last question, so I'm going to close this issue due to inactivity, but we can continue the discussion.

**Comment by kapstok** [comment]
I have the same problem only I have found a workaround. When building and running with:

```bash
dotnet build -t:Run ./MAUI\ DEMO/MAUI\ DEMO.csproj -f net7.0-maccatalyst
```

Key input doesn't work. But running the project seperately does allow for input detection:

```bash
dotnet build ./MAUI\ DEMO/MAUI\ DEMO.csproj -f net7.0-maccatalyst
./MAUI\ DEMO/bin/Debug/net7.0-maccatalyst/maccatalyst-arm64/MAUI\ DEMO.app/Contents/MacOS/MAUI\ DEMO
```

**Comment by demz20** [comment]
Hi @TolikPylypchuk , we have the same problem. Is there any possible solution to this now?

**Comment by TolikPylypchuk** [comment]
Hello @demz20, nope, I still haven't found a solution for this problem unfortunately.
