### ISSUE TITLE
Is it possible to determine the keyboard device name / id??

### ISSUE THREAD

**Issue by fsuk** [TolikPylypchuk/SharpHook#83]
I want to intercept key events from a barcode reader (serial coms not currently possible) which is emulating keyboard input.

Is it possible to filter keys events somehow to ignore events from the regular keyboard and only handle events from the scanner?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking! Unfortunately, this is not possible to do with libuiohook, and by extension, SharpHook as well. Here's a [related issue from libuiohook](https://github.com/kwhat/libuiohook/issues/63).

**Comment by fsuk** [comment]
> Hi! Thanks for asking! Unfortunately, this is not possible to do with libuiohook, and by extension, SharpHook as well. Here's a [related issue from libuiohook](https://github.com/kwhat/libuiohook/issues/63).

Thanks for your help. 

For others intrested after some googling I found this https://www.codeproject.com/Articles/716591/Combining-Raw-Input-and-keyboard-Hook-to-selective

However given the choice between this and getting the serial coms working in MAUI I think I'll give the serial coms a go.
