### ISSUE TITLE
Hook events stop working after using SendInput from the win32 API

### ISSUE THREAD

**Issue by Abdesol** [TolikPylypchuk/SharpHook#84]
In my project, I am using SharpHook for all the mouse and keyboard key events, and based on those, I am making certain mouse movements with the SendInput API from Win32 APIs. The hook events like the pressed and released work fine, but when I use SendInput, they stop responding.

OS: Win-11
Version: 5.2.3

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! This is definitely weird. Could you please try simulating mouse movement using SharpHook's `EventSimulator` and tell me whether the hooks stops working as well? I've never noticed such problems on my machine.

**Comment by Abdesol** [comment]
Yeah. Using `EventSimulator` fixes this issue. They are working together seamlessly now. But that doesn't work for my use case. The program in which I want to move the mouse doesn't work with EventSimulator. I have to use SendInput with low level API calling.

**Comment by TolikPylypchuk** [comment]
Could you please share a minimal reproducible example? So that I can try it out on my machine.

**Comment by TolikPylypchuk** [comment]
Hi @Abdesol! Any updates on the issue?

**Comment by TolikPylypchuk** [comment]
I'm going to close this issue due to inactivity, but we can reopen it any time.
