### ISSUE TITLE
Events for MouseMove are fired only after mouse stops moving.

### ISSUE THREAD

**Issue by andschir** [TolikPylypchuk/SharpHook#85]
Events for MouseMove are fired only after mouse stops moving completely.
If mouse never stops - no events are fired.

This behaviour is present for both reative and usual hooks.

Possible cause: using with from inside Avalonia UI app.

Is this expected? In my opinion move events should be fired soon-as-ready during actual mouse movement and, possibly, needed to throttle/sample.

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for posting this issue! This definitely sounds like a bug - mouse move events should be reported while the mouse is moving. Could you please tell me which OS you're using? Also, a minimal reproducible example would be nice.

**Comment by TolikPylypchuk** [comment]
I'm going to close this issue due to inactivity, but we can reopen it any time.
