### ISSUE TITLE
How to use in .NET Maui .NET 8.0

### ISSUE THREAD

**Issue by MathijsWouters** [TolikPylypchuk/SharpHook#86]
Hello i'm very new to coding and i'm trying to use this in net maui since i already made my program kind of once in winforms but there keydowns are easy. I know maui doesn't really support keydowns etc but is there anyway i can go around this i only need it working on the windows version of my app. Sorry if question is stupid.

**Comment by MathijsWouters** [comment]
I'll see what i can do thank you for the answer :)

**Comment by MathijsWouters** [comment]
`using System;
using SharpHook;
using SharpHook.Native;
using System.Diagnostics;


namespace Beursfuif.Models
{
#if WINDOWS
    public class KeyboardService
    {
        private IGlobalHook hook;

        public KeyboardService()
        {
            this.hook = new TaskPoolGlobalHook();

            this.hook.KeyPressed += OnKeyPressed;

        }

        private void OnKeyPressed(object sender, KeyboardHookEventArgs e)
        {
            if (e.Data.KeyCode == KeyCode.VcBackspace) 
            {
                Debug.WriteLine("backspace key pressed.");
            }
        }

        public void Start()
        {
            this.hook.Run();
        }

        public void Stop()
        {
            this.hook.Dispose();
        }
    }
#endif
}
using Beursfuif.Views;
using Beursfuif.Models;

namespace Beursfuif
{
    public partial class App : Application
    {
#if WINDOWS
        private KeyboardService keyboardService;
#endif
#if WINDOWS
        public App()
        {
            InitializeComponent();

            MainPage = new NavigationPage(new MainPage());
            try
            {

                this.keyboardService = new KeyboardService();
                this.keyboardService.Start();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception initializing KeyboardService: {ex.Message}");

            }
        }
#endif

        protected override void OnSleep()
        {

#if WINDOWS
            this.keyboardService?.Stop();
            base.OnSleep();
#endif

        }

    }
}
`
Well i'm trying to do it i have no errors but when i press backspace nothing happens

**Comment by TolikPylypchuk** [comment]
OK, thanks for providing an example, I will look into it soon.

**Comment by MathijsWouters** [comment]
If you need the full project for it i would gladly provide.

**Comment by TolikPylypchuk** [comment]
Hi @MathijsWouters! I've just tried to reproduce the problem, and everything works fine for me - the global hook works as expected. The only thing I would change in your code is calling `hook.RunAsync()` instead of `hook.Run()` inside `KeyboardService`. Calling `Run` will block the main thread so the app cannot finish its initialization.

Also, if you want your app to stop correctly when you close the main window, you should do one of two things:

- Handle the shutdown event and stop the global hook inside its handler.
- Create the global hook in the following way:

```c#
this.hook = new TaskPoolGlobalHook(new TaskPoolGlobalHookOptions(runAsyncOnBackgroundThread: true));
```

`runAsyncOnBackgroundThread: true` means that the global hook will run on a background thread which will not stop the application from exiting if other threads have finished executing.

I realize that since you're new to coding, the things I've described may seem advanced, but if you have more questions, then feel free to ask! Unfortunately, I'm not proficient with MAUI, so my help could be limited in that regard.

Also, if calling `RunAsync` instead of `Run` doesn't fix your problem, then please send a complete project which doesn't work and I will try to reproduce the problem on my machine.

**Comment by MathijsWouters** [comment]
With a little bit of tinkering i fixed so now i have working key presses in .Net maui thanks!

**Comment by TolikPylypchuk** [comment]
That's great! Could you also describe how you fixed the problem so that if someone else has the same problem, they'd know what to do to fix it?

**Comment by MathijsWouters** [comment]
Well tbh i have no clue what i did but i'll send some code. `using System;
using SharpHook;
using SharpHook.Native;
using System.Diagnostics;


namespace Beursfuif.Models
{
#if WINDOWS
    public class KeyboardService
    {
        private IGlobalHook hook;
        public Action OnBackspacePressed { get; set; }
        public Action<int> OnNumpadPressed { get; set; }

        public KeyboardService()
        {
            this.hook = new TaskPoolGlobalHook();
            this.hook.KeyPressed += OnKeyPressed;
            Debug.WriteLine("KeyboardService initialized and hook attached.");


        }

        private void OnKeyPressed(object sender, KeyboardHookEventArgs e)
        {
            if (e.Data.KeyCode == KeyCode.VcBackspace) 
            {
                Debug.WriteLine("backspace key pressed.");
               OnBackspacePressed?.Invoke();
            }
            else if (e.Data.KeyCode >= KeyCode.VcNumPad1 && e.Data.KeyCode <= KeyCode.VcNumPad9)
            {
                int drinkNumber = e.Data.KeyCode - KeyCode.VcNumPad1 + 1; 
                Debug.WriteLine($"Numpad {drinkNumber} key pressed.");
                OnNumpadPressed?.Invoke(drinkNumber);
            }
        }

        public void Start()
        {
            try
            {
                this.hook.RunAsync();
                Debug.WriteLine("Hook started.");
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Error starting hook: {ex.Message}");
            }
        }

        public void Stop()
        {
            try
            {
                this.hook.Dispose();
                Debug.WriteLine("Hook stopped.");
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Error stopping hook: {ex.Message}");
            }
        }

    }
#endif
}

`
`using Beursfuif.Models;
using System.Collections.Specialized;


namespace Beursfuif.Views;

public partial class MainPage : ContentPage

{
    private DrinksViewModel _viewModel;
    private Receipt _receipt = new Receipt();
#if WINDOWS
    private KeyboardService _keyboardService;
#endif

    public MainPage()
    {
        InitializeComponent();
        _viewModel = new DrinksViewModel();
        _receipt = new Receipt();
        BindingContext = _receipt;
        _viewModel.Drinks.CollectionChanged += Drinks_CollectionChanged;
        ReceiptListView.ItemsSource = _receipt.Items;

#if WINDOWS
        _keyboardService = new KeyboardService();
        _keyboardService.OnBackspacePressed = RemoveLastItemFromReceipt;
        _keyboardService.OnNumpadPressed = AddDrinkByNumber;
        _keyboardService.Start();
#endif`

**Comment by TolikPylypchuk** [comment]
Thanks! Also, I've edited your comment to format the code correctly, hope you don't mind :)

**Comment by MathijsWouters** [comment]
Yeah no problem i was trying myself but no luck xD. Thanks for your contribution to the community. 

Hope to see it implemented in .NET 9.0, because that would be way more easy and clean hahaha.

**Comment by MathijsWouters** [comment]
For anyone that wants to use this on maui it works perfectly on Windows and Macos if you just use the # statements.

Make sure in your viewmodels or your code behind you subscribe to the service in the constructor. Good luck!
[https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExd2d4cmZ6ZTVlNHkxNGZodmU0NXd5ZnN4OWUwN2xrM2R6YWJkNTFvbSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CuuSHzuc0O166MRfjt/giphy.gif](url)

**Comment by inescastro05** [comment]
hello, I need this example for android, is possible ?

**Comment by TolikPylypchuk** [comment]
Hi, @inescastro05, no, SharpHook doesn't work on Android, it only works on Windows, macOS, and Linux.
