### ISSUE TITLE
Handling keyboard shortcuts

### ISSUE THREAD

**Issue by Scorfox** [TolikPylypchuk/SharpHook#88]
Hi! Can I handle keyboard shortcuts (for example CTRL+TAB, ALT+ESC, etc) using your library?

**Comment by TolikPylypchuk** [comment]
Hi! Thanks for asking! SharpHook itself doesn't have any helper classes for handling key combinations, but it's absolutely possible to create your own, especially with SharpHook.Reactive.

As an example, you can look at how I use SharpHook.Reactive to handle key combinations of modifier keys (but it can be extended to any key) with the ability to handle multiple presses of the key combination (e.g. <kbd>Ctrl</kbd>+<kbd>Shift</kbd> pressed twice): https://github.com/TolikPylypchuk/KeyboardSwitch/blob/main/src/KeyboardSwitch.Core/Services/Hook/SharpHookService.cs

**Comment by Scorfox** [comment]
This looks cool! I'll try it, thanks!
