### ISSUE TITLE
[documentation] For OnMouseMoved, is e.Data.Y/X the final location, or the start?

### ISSUE THREAD

**Issue by AlexanderBlackman** [TolikPylypchuk/SharpHook#91]
I'm trying to work out the magnitude of the mouse movement.

Also, in general, listing the properties of each eventarg in the docs would be informative.

**Comment by TolikPylypchuk** [comment]
Hello! Thanks for asking! For mouse movement events the X/Y are the destination coordinates.

The [API docs](https://sharphook.tolik.io/v5.3.1/api/SharpHook.Native.MouseEventData.html) contain info on event data. Could you please be more specific - which properties do you have in mind that are missing in the docs?

**Comment by AlexanderBlackman** [comment]
> Hello! Thanks for asking! For mouse movement events the X/Y are the destination coordinates.
> 
> The [API docs](https://sharphook.tolik.io/v5.3.1/api/SharpHook.Native.MouseEventData.html) contain info on event data. Could you please be more specific - which properties do you have in mind that are missing in the docs?

Nevermind, I was mistaken, thank you for response.

**Comment by TolikPylypchuk** [comment]
Yeah, no problem!
