### ISSUE TITLE
SimulateMouseMovementRelative - X does not work, Y does.

### ISSUE THREAD

**Issue by ZeoWorks** [TolikPylypchuk/SharpHook#98]
Hi, when using SimulateMouseMovementRelative,
The X value always brings the cursor to the far right of the monitor.
Whereas the Y value works fine and moves as intended.

inputSimulator.SimulateMouseMovementRelative((short)1,(short)1);
^ Snaps the cursor to the right side of the screen, moves the cursor on Y axis down 1.

**Comment by TolikPylypchuk** [comment]
Hello! Thanks for posting this issue! Could you please specify which OS you're using? So that I can try to reproduce it.

**Comment by TolikPylypchuk** [comment]
I've tried reproducing this on Windows and everything works fine for me. Could you please also share a minimal reproducible example?

**Comment by clFaster** [comment]
I do have the same issue under Windows 11 with two QHD Monitors connected, maybe related #100?
Similar behaviour also with `SimulateMouseMovement` - mouse jumps always to the right edge

**Comment by TolikPylypchuk** [comment]
Hm, yeah, could be the same issue. I couldn't reproduce it because I've tried it out on a single monitor. Will try again with multiple monitors.

**Comment by TolikPylypchuk** [comment]
I have fixed the issue and will release a new version with the fix soon.

**Comment by TolikPylypchuk** [comment]
I've just released version 5.3.3 which fixes this bug, so this issue can be closed.
